// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801022356_GeantsData2")]
    partial class GeantsData2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("number");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("tblAccount");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Printing & Binding",
                            Number = "11-102-0312-54700"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Insurance-Other",
                            Number = "11-102-0312-54701"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Freight & Postage Service",
                            Number = "11-102-0312-54702"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Communication Services",
                            Number = "11-102-0312-54703"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Rentals & Lease",
                            Number = "11-102-0312-54704"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Utilities - Electric",
                            Number = "11-102-0312-54705"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Name = "Toner",
                            Number = "11-102-0312-54706"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "Pens",
                            Number = "11-102-0312-54707"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Erasers",
                            Number = "11-102-0312-54708"
                        });
                });

            modelBuilder.Entity("Domain.AuthorizedUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime")
                        .HasColumnName("last_login_date");

                    b.Property<string>("WindowsLogin")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("windows_login");

                    b.HasKey("Id");

                    b.ToTable("tblAuthorizedUsers");
                });

            modelBuilder.Entity("Domain.BudgetLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id")
                        .HasColumnOrder(3);

                    b.Property<double>("Amount")
                        .HasColumnType("float")
                        .HasColumnName("amount")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("create_date")
                        .HasColumnOrder(7);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by")
                        .HasColumnOrder(6);

                    b.Property<int>("GrantId")
                        .HasColumnType("int")
                        .HasColumnName("grant_id")
                        .HasColumnOrder(2);

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int")
                        .HasColumnName("initiative_id")
                        .HasColumnOrder(1);

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item_type")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date")
                        .HasColumnOrder(9);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(8);

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("GrantId");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("tblBudget");
                });

            modelBuilder.Entity("Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tblCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Services"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Facilities"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Supplies"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Personnel"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fringe"
                        });
                });

            modelBuilder.Entity("Domain.Grant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<string>("Fiduciary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fiduciary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.ToTable("tblGrant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2028, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiduciary = "MSCO",
                            Name = "G26001",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2028, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiduciary = "Cameron Co",
                            Name = "G26001",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Initiative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tblInitiative");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Management & Coordination"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Training"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Multemedia & Technology"
                        });
                });

            modelBuilder.Entity("Domain.Account", b =>
                {
                    b.HasOne("Domain.Category", "Category")
                        .WithMany("Accounts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.BudgetLineItem", b =>
                {
                    b.HasOne("Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.AuthorizedUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Grant", "Grant")
                        .WithMany()
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Initiative", "Initiative")
                        .WithMany()
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.AuthorizedUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("Account");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Grant");

                    b.Navigation("Initiative");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Domain.Category", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
