// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002140010_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("number");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("tblAccount");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Salaries",
                            Number = "1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Name = "Janitorial",
                            Number = "1"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Rentals and Leases",
                            Number = "1"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Utilities Services - Electric",
                            Number = "1"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "FICA",
                            Number = "1"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Life & Health Insurance",
                            Number = "1"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Name = "Insurance Fringe",
                            Number = "1"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "Retirement",
                            Number = "1"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Workers Comp",
                            Number = "1"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Name = "Equipment - Over $5,000",
                            Number = "1"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            Name = "Contractors",
                            Number = "1"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            Name = "Insurance Other",
                            Number = "1"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 6,
                            Name = "Freight and Postage Services",
                            Number = "1"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 6,
                            Name = "Communication Services",
                            Number = "1"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 6,
                            Name = "Other Contractual Services",
                            Number = "1"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 7,
                            Name = "Office",
                            Number = "1"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 7,
                            Name = "Software",
                            Number = "1"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 7,
                            Name = "Machinery and Equipment ($1,000 to $5,000)",
                            Number = "1"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 8,
                            Name = "Contractor",
                            Number = "1"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 9,
                            Name = "Agency",
                            Number = "1"
                        });
                });

            modelBuilder.Entity("Domain.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Auth.tblRoles", (string)null);
                });

            modelBuilder.Entity("Domain.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Auth.tblUsers", (string)null);
                });

            modelBuilder.Entity("Domain.AuthorizedUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime")
                        .HasColumnName("last_login_date");

                    b.Property<string>("WindowsLogin")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("windows_login");

                    b.HasKey("Id");

                    b.ToTable("tblAuthorizedUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            WindowsLogin = "hialfonso"
                        },
                        new
                        {
                            Id = 2,
                            WindowsLogin = "rxleopold"
                        },
                        new
                        {
                            Id = 3,
                            WindowsLogin = "rescobar"
                        });
                });

            modelBuilder.Entity("Domain.BudgetComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("entry_date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("EntryPersonId")
                        .HasColumnType("int")
                        .HasColumnName("entry_user_id");

                    b.Property<int>("GrantId")
                        .HasColumnType("int")
                        .HasColumnName("grant_id");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int")
                        .HasColumnName("initiative_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("comment_text");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("update_date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("UpdatePersonId")
                        .HasColumnType("int")
                        .HasColumnName("update_user_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("EntryPersonId");

                    b.HasIndex("GrantId");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("UpdatePersonId");

                    b.ToTable("tblBudgetComment");
                });

            modelBuilder.Entity("Domain.BudgetItemType", b =>
                {
                    b.Property<string>("ItemType")
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("item_type");

                    b.HasKey("ItemType");

                    b.ToTable("tblBudgetItemType");

                    b.HasData(
                        new
                        {
                            ItemType = "B"
                        },
                        new
                        {
                            ItemType = "R"
                        },
                        new
                        {
                            ItemType = "D"
                        });
                });

            modelBuilder.Entity("Domain.BudgetLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id")
                        .HasColumnOrder(3);

                    b.Property<decimal>("Amount")
                        .HasColumnType("NUMERIC(15,2)")
                        .HasColumnName("amount")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("create_date")
                        .HasColumnOrder(8);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by")
                        .HasColumnOrder(7);

                    b.Property<int>("GrantId")
                        .HasColumnType("int")
                        .HasColumnName("grant_id")
                        .HasColumnOrder(2);

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int")
                        .HasColumnName("initiative_id")
                        .HasColumnOrder(1);

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("item_type")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("update_date")
                        .HasColumnOrder(10);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(9);

                    b.Property<short>("Year")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("year")
                        .HasColumnOrder(6);

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("GrantId");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("ItemType");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("tblBudget");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Amount = 100m,
                            CreateDate = new DateTime(2026, 7, 31, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            GrantId = 1,
                            InitiativeId = 1,
                            ItemType = "B",
                            Year = (short)2025
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 3,
                            Amount = 100m,
                            CreateDate = new DateTime(2026, 7, 31, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            GrantId = 1,
                            InitiativeId = 1,
                            ItemType = "B",
                            Year = (short)2025
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 4,
                            Amount = 105m,
                            CreateDate = new DateTime(2026, 7, 31, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            GrantId = 1,
                            InitiativeId = 1,
                            ItemType = "B",
                            Year = (short)2025
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 7,
                            Amount = 1200m,
                            CreateDate = new DateTime(2026, 7, 31, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            GrantId = 1,
                            InitiativeId = 1,
                            ItemType = "B",
                            Year = (short)2025
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 8,
                            Amount = 400m,
                            CreateDate = new DateTime(2026, 7, 31, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            GrantId = 1,
                            InitiativeId = 1,
                            ItemType = "B",
                            Year = (short)2025
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 5,
                            Amount = 596.0m,
                            CreateDate = new DateTime(2026, 7, 31, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            GrantId = 1,
                            InitiativeId = 1,
                            ItemType = "B",
                            Year = (short)2025
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 8,
                            Amount = 400m,
                            CreateDate = new DateTime(2026, 7, 31, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            GrantId = 1,
                            InitiativeId = 2,
                            ItemType = "B",
                            Year = (short)2025
                        },
                        new
                        {
                            Id = 10,
                            AccountId = 5,
                            Amount = 750m,
                            CreateDate = new DateTime(2026, 7, 31, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            GrantId = 3,
                            InitiativeId = 1,
                            ItemType = "B",
                            Year = (short)2026
                        },
                        new
                        {
                            Id = 11,
                            AccountId = 8,
                            Amount = 250m,
                            CreateDate = new DateTime(2026, 7, 31, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            GrantId = 3,
                            InitiativeId = 2,
                            ItemType = "B",
                            Year = (short)2026
                        },
                        new
                        {
                            Id = 12,
                            AccountId = 8,
                            Amount = 250m,
                            CreateDate = new DateTime(2026, 7, 31, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            GrantId = 3,
                            InitiativeId = 2,
                            ItemType = "B",
                            Year = (short)2026
                        },
                        new
                        {
                            Id = 13,
                            AccountId = 1,
                            Amount = -50m,
                            CreateDate = new DateTime(2026, 7, 31, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            GrantId = 1,
                            InitiativeId = 1,
                            ItemType = "D",
                            Year = (short)2025
                        });
                });

            modelBuilder.Entity("Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("tblCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Personnel",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Facilities",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fringe",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Equipment",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Services Contractors",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "Services Contractors",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "Supplies",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            Name = "Travel Contractor",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            Name = "Travel Agency",
                            SortOrder = 9
                        });
                });

            modelBuilder.Entity("Domain.Contrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)")
                        .HasColumnName("firstName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)")
                        .HasColumnName("lastName");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("tblContrator");
                });

            modelBuilder.Entity("Domain.Disb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("NUMERIC(15,2)")
                        .HasColumnName("amount");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("create_date");

                    b.Property<int?>("GrantId")
                        .HasColumnType("int");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("justification");

                    b.Property<bool>("Posted")
                        .HasColumnType("bit")
                        .HasColumnName("posted");

                    b.Property<int?>("PostedById")
                        .HasColumnType("int")
                        .HasColumnName("posted_by");

                    b.Property<DateTime?>("PostedDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("posted_date");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("updated_date");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("GrantId");

                    b.HasIndex("PostedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("tblDisb");
                });

            modelBuilder.Entity("Domain.DisbLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("NUMERIC(15,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("BudgetLineItemId")
                        .HasColumnType("int")
                        .HasColumnName("budget_line_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("Comment")
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("comment");

                    b.Property<int>("DisbId")
                        .HasColumnType("int")
                        .HasColumnName("disb_id");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("entry_date");

                    b.Property<int>("GrantId")
                        .HasColumnType("int")
                        .HasColumnName("grant_id");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int")
                        .HasColumnName("initiative_id");

                    b.Property<int>("PayeeId")
                        .HasColumnType("int")
                        .HasColumnName("payee_id");

                    b.Property<int>("RowId")
                        .HasColumnType("int")
                        .HasColumnName("row_id");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("update_date");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BudgetLineItemId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GrantId");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("PayeeId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("DisbId", "InitiativeId", "GrantId", "CategoryId", "AccountId")
                        .IsUnique();

                    b.ToTable("tblDisbLineItem");
                });

            modelBuilder.Entity("Domain.Grant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<string>("Fiduciary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fiduciary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tblGrant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiduciary = "MSCO",
                            Name = "G25001",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Year = 2025
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiduciary = "Cameron Co",
                            Name = "G25002",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Year = 2025
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2027, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiduciary = "MCSO",
                            Name = "G26001",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Year = 2026
                        },
                        new
                        {
                            Id = 4,
                            EndDate = new DateTime(2027, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiduciary = "Cameron Co",
                            Name = "G26002",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Year = 2026
                        });
                });

            modelBuilder.Entity("Domain.Initiative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tblInitiative");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Management & Coordination"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Training"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ORS"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Multimedia & Technology Unit"
                        },
                        new
                        {
                            Id = 5,
                            Name = "DHE"
                        },
                        new
                        {
                            Id = 6,
                            Name = "DTAG"
                        });
                });

            modelBuilder.Entity("Domain.Payee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("tblPayee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 13,
                            IsActive = true,
                            Name = "Kinkos"
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 13,
                            IsActive = true,
                            Name = "FedEx"
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 13,
                            IsActive = true,
                            Name = "Shipstation"
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 13,
                            IsActive = true,
                            Name = "Navis Pack & Ship"
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 13,
                            IsActive = true,
                            Name = "ShippyPro"
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 13,
                            IsActive = true,
                            Name = "Mimeo"
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 13,
                            IsActive = true,
                            Name = "EasySip"
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 13,
                            IsActive = true,
                            Name = "PackAndShip"
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 14,
                            IsActive = true,
                            Name = "AT & T"
                        },
                        new
                        {
                            Id = 10,
                            AccountId = 14,
                            IsActive = true,
                            Name = "Comcast"
                        },
                        new
                        {
                            Id = 11,
                            AccountId = 14,
                            IsActive = true,
                            Name = "Sunshine"
                        },
                        new
                        {
                            Id = 12,
                            AccountId = 14,
                            IsActive = true,
                            Name = "Motorola"
                        },
                        new
                        {
                            Id = 13,
                            AccountId = 14,
                            IsActive = true,
                            Name = "Voip Comm"
                        },
                        new
                        {
                            Id = 14,
                            AccountId = 19,
                            IsActive = true,
                            Name = "Tom Sanchez"
                        },
                        new
                        {
                            Id = 15,
                            AccountId = 19,
                            IsActive = true,
                            Name = "Marc Greenstien"
                        },
                        new
                        {
                            Id = 16,
                            AccountId = 19,
                            IsActive = true,
                            Name = "Troy Bankert"
                        },
                        new
                        {
                            Id = 17,
                            AccountId = 19,
                            IsActive = true,
                            Name = "Charles Bengston"
                        },
                        new
                        {
                            Id = 18,
                            AccountId = 19,
                            IsActive = true,
                            Name = "Ethan Steigerwald"
                        },
                        new
                        {
                            Id = 19,
                            AccountId = 19,
                            IsActive = true,
                            Name = "Steve Sales"
                        },
                        new
                        {
                            Id = 20,
                            AccountId = 19,
                            IsActive = true,
                            Name = "Tim Cardwell"
                        },
                        new
                        {
                            Id = 21,
                            AccountId = 19,
                            IsActive = true,
                            Name = "Tafoya Martina"
                        },
                        new
                        {
                            Id = 22,
                            AccountId = 19,
                            IsActive = true,
                            Name = "Jim Cormier"
                        },
                        new
                        {
                            Id = 23,
                            AccountId = 19,
                            IsActive = true,
                            Name = "Shaun Doyne"
                        },
                        new
                        {
                            Id = 24,
                            AccountId = 19,
                            IsActive = true,
                            Name = "John Eadie"
                        },
                        new
                        {
                            Id = 25,
                            AccountId = 19,
                            IsActive = true,
                            Name = "Orman Hall"
                        },
                        new
                        {
                            Id = 26,
                            AccountId = 19,
                            IsActive = true,
                            Name = "David Hamby"
                        },
                        new
                        {
                            Id = 27,
                            AccountId = 19,
                            IsActive = true,
                            Name = "Christopher Jakim"
                        },
                        new
                        {
                            Id = 28,
                            AccountId = 19,
                            IsActive = true,
                            Name = "Emma Kempton"
                        },
                        new
                        {
                            Id = 29,
                            AccountId = 19,
                            IsActive = true,
                            Name = "Rob Roggeveen"
                        },
                        new
                        {
                            Id = 30,
                            AccountId = 19,
                            IsActive = true,
                            Name = "Steve Salas"
                        },
                        new
                        {
                            Id = 31,
                            AccountId = 19,
                            IsActive = true,
                            Name = "Mike Snyders"
                        });
                });

            modelBuilder.Entity("Domain.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("CategoryId")
                        .HasColumnType("tinyint")
                        .HasColumnName("category_id");

                    b.Property<string>("DefaultFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("default_download_filename");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("VARCHAR(1000)")
                        .HasColumnName("path");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("tblReport", "Report");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = (byte)1,
                            DefaultFileName = "GrantBalanceByInitiativeAndAR",
                            Enabled = true,
                            Name = "Grant Balance By Initiative and AR",
                            Path = "/GrantBalanceByInitiativeAndAR"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = (byte)1,
                            DefaultFileName = "BudgetDetail",
                            Enabled = true,
                            Name = "Budget Detail",
                            Path = "/BudgetDetail"
                        });
                });

            modelBuilder.Entity("Domain.ReportCategory", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("name");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("tinyint")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("tblReportCategory", "Report");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "NHAC",
                            SortOrder = (byte)1
                        });
                });

            modelBuilder.Entity("Domain.ReportParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ControlType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("control_type");

                    b.Property<string>("DependsOn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("depends_on");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("enabled");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(75)")
                        .HasColumnName("name");

                    b.Property<int>("ReportId")
                        .HasColumnType("int")
                        .HasColumnName("report_id");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("tinyint")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ReportId", "SortOrder")
                        .IsUnique();

                    b.ToTable("tblReportParamter", "Report");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ControlType = "dropdownlist",
                            Enabled = true,
                            Label = "Year",
                            Name = "aiYear",
                            ReportId = 1,
                            SortOrder = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            ControlType = "checkboxlist",
                            Enabled = true,
                            Label = "Initiative",
                            Name = "avcInitiatives",
                            ReportId = 1,
                            SortOrder = (byte)2
                        },
                        new
                        {
                            Id = 3,
                            ControlType = "dropdownlist",
                            Enabled = true,
                            Label = "Year",
                            Name = "aiYear",
                            ReportId = 2,
                            SortOrder = (byte)1
                        },
                        new
                        {
                            Id = 4,
                            ControlType = "checkboxlist",
                            DependsOn = "aiYear",
                            Enabled = true,
                            Label = "Grant",
                            Name = "avcGrants",
                            ReportId = 2,
                            SortOrder = (byte)2
                        },
                        new
                        {
                            Id = 5,
                            ControlType = "dropdownlist",
                            Enabled = true,
                            Label = "Budget Category",
                            Name = "aiBudgetCat",
                            ReportId = 2,
                            SortOrder = (byte)3
                        });
                });

            modelBuilder.Entity("Domain.Repro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("NUMERIC(15,2)")
                        .HasColumnName("amount");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("create_date");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("justification");

                    b.Property<bool>("Posted")
                        .HasColumnType("bit")
                        .HasColumnName("posted");

                    b.Property<int?>("PostedById")
                        .HasColumnType("int")
                        .HasColumnName("posted_by");

                    b.Property<DateTime?>("PostedDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("posted_date");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("updated_date");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PostedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("tblRepro");
                });

            modelBuilder.Entity("Domain.ReproLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<bool?>("AllowNegativeBalance")
                        .HasColumnType("bit")
                        .HasColumnName("allow_neg_balance");

                    b.Property<int?>("BudgetLineItemId")
                        .HasColumnType("int")
                        .HasColumnName("budget_line_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("Comment")
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("comment");

                    b.Property<decimal?>("Decrease")
                        .HasColumnType("NUMERIC(15,2)")
                        .HasColumnName("decrease");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("entry_date");

                    b.Property<int>("GrantId")
                        .HasColumnType("int")
                        .HasColumnName("grant_id");

                    b.Property<decimal?>("Increase")
                        .HasColumnType("NUMERIC(15,2)")
                        .HasColumnName("increase");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int")
                        .HasColumnName("initiative_id");

                    b.Property<int>("ReproId")
                        .HasColumnType("int")
                        .HasColumnName("repro_id");

                    b.Property<int>("RowId")
                        .HasColumnType("int")
                        .HasColumnName("row_id");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("update_date");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BudgetLineItemId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GrantId");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("ReproId", "InitiativeId", "GrantId", "CategoryId", "AccountId")
                        .IsUnique();

                    b.ToTable("tblReproLineItem");
                });

            modelBuilder.Entity("Domain.Views.PayeeSummary", b =>
                {
                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DaysSinceLastPayment")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastPayment")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView("vwVendorSummary", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Auth.tblRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Auth.tblUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("Auth.tblUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("Auth.tblUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("Auth.tblUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Account", b =>
                {
                    b.HasOne("Domain.Category", "Category")
                        .WithMany("Accounts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.BudgetComment", b =>
                {
                    b.HasOne("Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.AuthorizedUser", "EntryPerson")
                        .WithMany()
                        .HasForeignKey("EntryPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Grant", "Grant")
                        .WithMany()
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Initiative", "Initiative")
                        .WithMany()
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.AuthorizedUser", "UpdatePerson")
                        .WithMany()
                        .HasForeignKey("UpdatePersonId");

                    b.Navigation("Account");

                    b.Navigation("EntryPerson");

                    b.Navigation("Grant");

                    b.Navigation("Initiative");

                    b.Navigation("UpdatePerson");
                });

            modelBuilder.Entity("Domain.BudgetLineItem", b =>
                {
                    b.HasOne("Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.AuthorizedUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Grant", "Grant")
                        .WithMany()
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Initiative", "Initiative")
                        .WithMany()
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.BudgetItemType", "BudgetItemType")
                        .WithMany("BudgetLineItems")
                        .HasForeignKey("ItemType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.AuthorizedUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("Account");

                    b.Navigation("BudgetItemType");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Grant");

                    b.Navigation("Initiative");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Domain.Contrator", b =>
                {
                    b.HasOne("Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Domain.Disb", b =>
                {
                    b.HasOne("Domain.AuthorizedUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Grant", null)
                        .WithMany("Disbs")
                        .HasForeignKey("GrantId");

                    b.HasOne("Domain.AuthorizedUser", "PostedBy")
                        .WithMany()
                        .HasForeignKey("PostedById");

                    b.HasOne("Domain.AuthorizedUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("PostedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Domain.DisbLineItem", b =>
                {
                    b.HasOne("Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.BudgetLineItem", "BudgetLineItem")
                        .WithMany()
                        .HasForeignKey("BudgetLineItemId");

                    b.HasOne("Domain.Category", "Category")
                        .WithMany("DisbLineItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Disb", "Disb")
                        .WithMany("Items")
                        .HasForeignKey("DisbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Grant", "Grant")
                        .WithMany()
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Initiative", "Initiative")
                        .WithMany()
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Payee", "Payee")
                        .WithMany("DisbLineItems")
                        .HasForeignKey("PayeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.AuthorizedUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("Account");

                    b.Navigation("BudgetLineItem");

                    b.Navigation("Category");

                    b.Navigation("Disb");

                    b.Navigation("Grant");

                    b.Navigation("Initiative");

                    b.Navigation("Payee");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Domain.Payee", b =>
                {
                    b.HasOne("Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Domain.Report", b =>
                {
                    b.HasOne("Domain.ReportCategory", "Category")
                        .WithMany("Reports")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.ReportParameter", b =>
                {
                    b.HasOne("Domain.Report", "Report")
                        .WithMany("Parameters")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Domain.Repro", b =>
                {
                    b.HasOne("Domain.AuthorizedUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.AuthorizedUser", "PostedBy")
                        .WithMany()
                        .HasForeignKey("PostedById");

                    b.HasOne("Domain.AuthorizedUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("PostedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Domain.ReproLineItem", b =>
                {
                    b.HasOne("Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.BudgetLineItem", "BudgetLineItem")
                        .WithMany()
                        .HasForeignKey("BudgetLineItemId");

                    b.HasOne("Domain.Category", "Category")
                        .WithMany("ReproLineItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Grant", "Grant")
                        .WithMany()
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Initiative", "Initiative")
                        .WithMany()
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Repro", "Repro")
                        .WithMany("Items")
                        .HasForeignKey("ReproId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.AuthorizedUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("Account");

                    b.Navigation("BudgetLineItem");

                    b.Navigation("Category");

                    b.Navigation("Grant");

                    b.Navigation("Initiative");

                    b.Navigation("Repro");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Domain.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Domain.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.BudgetItemType", b =>
                {
                    b.Navigation("BudgetLineItems");
                });

            modelBuilder.Entity("Domain.Category", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("DisbLineItems");

                    b.Navigation("ReproLineItems");
                });

            modelBuilder.Entity("Domain.Disb", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domain.Grant", b =>
                {
                    b.Navigation("Disbs");
                });

            modelBuilder.Entity("Domain.Payee", b =>
                {
                    b.Navigation("DisbLineItems");
                });

            modelBuilder.Entity("Domain.Report", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Domain.ReportCategory", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Domain.Repro", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
